### ISSUE TITLE
Windows HPC is not constrained by the Windows host-to-container version support matrix; the nodeselector can be removed

### ISSUE THREAD

**Issue by doctorpangloss** [TensorWorks/DirectX-Device-Plugins#1]
https://github.com/TensorWorks/DirectX-Device-Plugins/blob/7ee9ff34a8003bc5038c881178aa097837a37536/deployments/default-daemonsets.yml#L19

You will be able to support 2019 and 2022 hosts with a single daemonset here, as long as you are using hostprocess containers.

**Comment by adamrehn** [comment]
Although the container images used for Windows HostProcess containers do not need to match the host version of Windows that those containers will run on, the Kubernetes scheduler will still enforce node selectors related to the Windows version number if they are specified for Pods that include HostProcess containers. The node selectors specified in the default DaemonSets for the device plugins rely on this behaviour to explicitly ***prevent*** the plugins from being scheduled on Windows Server 2019 worker nodes.

Windows Server 2022 is the minimum version required by the Kubernetes Device Plugins for DirectX. Windows Server 2019 is not supported, for two reasons:

- It does not support the [Host Compute Service (HCS)](https://learn.microsoft.com/en-us/virtualization/api/hcs/overview) 2.2 schema required to expose individual device to containers using the `vpci-location-path://PATH` device string syntax. Attempting to expose a device using this syntax under Windows Server 2019 will result in an error, since the HCS will reject the generated [Container](https://learn.microsoft.com/en-us/virtualization/api/hcs/schemareference#Container) document.

- It does not support the [DXCore](https://learn.microsoft.com/en-us/windows/win32/dxcore/dxcore) API that the Device Discovery Library uses to enumerate DirectX devices. If the device plugins are run under Windows Server 2019, they will crash on startup due to the absence of `dxcore.dll`.

The inclusion of the node selector prevents issues from arising when the device plugins are deployed to a Kubernetes cluster that includes both Windows Server 2019 and Windows Server 2022 worker nodes. The plugins will only be scheduled on the Windows Server 2022 worker nodes, and the incompatible Windows Server 2019 worker nodes will be safely ignored.
